### PR TITLE
Scuffed Tic Tac Toe

### PR DESCRIPTION
**Pull request by milkshake-moo**
adding in old scuffed tic tac toe game code

### CODE REVIEW

**Comment by milkshake-moo** [comment]
This relates to #2

**Comment by milkshake-moo** [comment]
There is absolutely no guarantee this runs successfully, but why not try and put the code up here to use as inspiration/overview?

Also don't even worry about the fact that it crashes when you try a 0-player game. It's _finneeeeee_

**Comment by donny138** [comment]
This looks great!  I'll have to try and run this and let you know how badly it crashes!  

It will make for some good inspiration / reference code for how python gui / graphics stuff works at the very least!

**Review by donny138 — COMMENTED** [review]
Official approval!  

There's a lot in here!

**Review by donny138 — APPROVED** [review]

**Pull request merged**
